name = "CosmoMIA"
uuid = "52f8af5a-f538-4ca3-835f-6229d6733639"
authors = ["Daniel Forero-Sánchez"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
